사장님 관련 기능 추가
SHSongs/cheese-shop pull request #19
Opened 2023-09-19 13:40 UTC by ycheese

# GET /owner/reservations
- 예약 목록을 모두 조회합니다.
## 응답 예시
```
[
    {
        "id": 1,
        "user": {
            "name": "윤채은",
            "phone": "1234"
        },
        "date": "20230919",
        "time": "1500",
        "guests": "4",
        "isClosed": true,
        "isPaied": false
    },
    {
        "id": 2,
        "user": {
            "name": "서윤지",
            "phone": "2424"
        },
        "date": "20230918",
        "time": "1500",
        "guests": "100",
        "isClosed": false,
        "isPaied": false
    }
]
```
# PUT /owner/reservations/${reservationId}
- 예약을 종료합니다.
## 응답 예시
```
{
    "id": 1,
    "user": {
        "name": "윤채은",
        "phone": "1234"
    },
    "date": "20230919",
    "time": "1500",
    "guests": "4",
    "isClosed": true,
    "isPaied": false
}
```
# GET /owner/reviews
- 리뷰 목록을 모두 조회합니다.
## 응답 예시
```
[
    {
        "reservation_id": 1,
        "point": "5",
        "content": "인생 식당. 최고의 맛이에요."
    },
    {
        "reservation_id": 2,
        "point": "2",
        "content": "너무 짜고 화장실이 지저분해요."
    }
]
```

2023-09-19 15:40 UTC, hatchling13 requested changes
이외의 부분은 실제로 돌려보고 문제가 있는지 파악할 수 있을 것 같아요~

2023-09-19 22:09 UTC, darkenpeng reviewed
👍

2023-09-20 01:01 UTC, ycheese commented on src/resources/reservation.json
제 실수입니다 .. 😢

2023-09-20 01:58 UTC, hatchling13 commented on src/main/scala/service/OwnerService.scala
> +  def getReservations() = for {
파일에 접근하는 함수들 관련해서 이야기하고 싶은 게 있는데, 이 부분은 제가 작성한 코드 PR 쪽에서 이야기해보도록 하죵

2023-09-20 01:58 UTC, hatchling13 approved these changes
👍

2023-09-20 01:59 UTC, merged