예약 기능 개발
SHSongs/cheese-shop pull request #21
Opened 2023-09-20 11:25 UTC by darkenpeng

close #14 

예약 하나 당 리뷰 하나만 남길 수 있는 기능을 추가했습니다. 
saveReview를 별도의 함수로 분리했습니다.

2023-09-20 11:56 UTC, ycheese requested changes
정욱님 코드랑 겹쳐 보여서 제가 윤지님 변경사항이 아닌 곳에 코멘트 드렸을 수 있습니다.
윤지님 코드가 아닌 부분은 흐린 눈 하고 봐주세요 🙏

2023-09-20 11:56 UTC, ycheese commented on src/main/scala/service/UserService.scala
> +    _ <- saveReview(nextReviews)
이미 리뷰가 있는 경우 어떻게 동작하나요?
ZIO.fail을 만나서 71Line에 saveReview를 호출하지 않는 건가요?
리뷰가 있을 때 저장된 리뷰(getReviews()를 통해 가져온 내용)을 그대로 다시 저장하는거라면 불필요한 파일 접근이 될 것 같아서 여쭤봅니다 ~

2023-09-20 11:56 UTC, ycheese commented on src/main/scala/service/UserService.scala
>    } yield ()
저장된 리뷰를 리턴해서 response body에 담아줄 수 있도록 하면 어떨까요?

2023-09-20 11:56 UTC, ycheese commented on src/main/scala/service/UserService.scala
> +  def saveReview(nextReviews: List[Review]) = for {
writeReview, addReview, saveReview가 이름만 봐선 혼동이 있을 것 같습니다.
Controller에 공개할 메소드를 정해서 메소드의 접근 제어자 수정도 필요해 보이네요~

2023-09-20 12:02 UTC, darkenpeng commented on src/main/scala/service/UserService.scala
> +  def saveReview(nextReviews: List[Review]) = for {
@hatchling13 이부분은 정욱님께 토스하겠습니다

2023-09-20 12:05 UTC, ycheese commented on src/main/scala/service/UserService.scala
>    } yield ()
단순 의견제시였습니다 ..! 지나가셔도 좋습니다

2023-09-20 12:36 UTC, hatchling13 requested changes
당장 명시적으로 변경을 요구드리는 부분은 `addReview`, `saveReview`의 `private`화, `writeReview`의 공개입니다. `write`가 실제로 Controller에서 쓰일 함수라는 주석을 달아주는 것도 좋겠네요.

L71의 부분은 좀 고민해볼 필요가 있을 것 같네요.

`...ById` 관련해서는 일종의 취향이라고 볼 수도 있을 것 같아서 굳이 수정 요청까지는 드릴 필요 없을 것 같습니다.

2023-09-20 12:36 UTC, hatchling13 commented on src/main/scala/service/UserService.scala
> +  private def findReservationById(id : Int) = for{
이미 `get...` 접두어가 붙은(`FileManager.readJson`을 이용하는) 함수들이 존재하고 있습니다.
만약 해당 코드들(`...ById` 접미어가 붙은)이 내부적으로만 사용되는 코드라면, 얻은 데이터에 고차 함수 적용 한 번만 하는 동작들은 따로 빼는 것보다 그대로 써주는 게 좀 더 자연스럽다고 생각합니다.

2023-09-20 12:36 UTC, hatchling13 commented on src/main/scala/service/UserService.scala
> +  private def checkIfReservationExistById(targetId : Int) = for{
`...ById` 접미어가 붙은 코드는 위에서 말한 바 있습니다.

2023-09-20 12:36 UTC, hatchling13 commented on src/main/scala/service/UserService.scala
> +    _ <- saveReview(nextReviews)
사용자가 해당 기능을 실행했을 때, (서버 오류가 아니라면) 작업이 성공했는지 실패했는지 여부를 알 수 있어야 한다고 봅니다. 따라서 Controller가 특정 기능의 수행 결과를 알 수 있어야 할 거 같아요. Controller에게 전달될 수 있는 결과는 반환된 값 뿐이니, 이 부분을 좀 생각해볼 필요가 있겠네요.

저도 마찬가지로 코드를 수정할 필요가 있는 것 같습니다.

2023-09-20 12:42 UTC, hatchling13 commented on src/main/scala/service/UserService.scala
> +  private def findReservationById(id : Int) = for{
헉 이제보니 저도 이런식으로 하고 있었던 것 같기도...? 제 발에 제가 걸려넘어졌네요 ㅋㅋㅋㅋㅋㅋ

2023-09-22 03:53 UTC, darkenpeng commented on src/main/scala/service/UserService.scala
> +  private def findReservationById(id : Int) = for{
그럼 같이 맞출까요? 저는 정욱님 코드 보고 함수로 분리했어요

2023-09-22 03:54 UTC, darkenpeng commented on src/main/scala/service/UserService.scala
> +    _ <- saveReview(nextReviews)
Issue #23 created

2023-09-22 08:44 UTC, hatchling13 commented on src/main/scala/service/UserService.scala
> +  private def findReservationById(id : Int) = for{
넵 다만 실제로 파일에 접근하는 함수(`readJson`, `writeJson`)을 최대한 활용하는 방향으로 가고 싶습니다. 저도 단순 데이터 매핑 코드들(`getClosedReservationsOfUser`(L111), `getPaidButNotReviewedReservationsOfUser`(L133))같은 건 전체를 얻어와주는 `get` 접두어가 붙은 함수들을 사용하게 작성한 바 있기 때문에, 이런 쪽으로 맞춰주시면 좋을 것 같아요.

2023-09-23 02:07 UTC, merged

2023-09-23 03:03 UTC, darkenpeng commented on src/main/scala/service/UserService.scala
> +    _ <- saveReview(nextReviews)
> 이미 리뷰가 있는 경우 어떻게 동작하나요? ZIO.fail을 만나서 71Line에 saveReview를 호출하지 않는 건가요? 리뷰가 있을 때 저장된 리뷰(getReviews()를 통해 가져온 내용)을 그대로 다시 저장하는거라면 불필요한 파일 접근이 될 것 같아서 여쭤봅니다 ~

ZIO.fail로 감싸져있어서 saveReview를 호출하지 않습니다!

2023-09-23 03:07 UTC, darkenpeng commented on src/main/scala/service/UserService.scala
> +    _ <- saveReview(nextReviews)
> 사용자가 해당 기능을 실행했을 때, (서버 오류가 아니라면) 작업이 성공했는지 실패했는지 여부를 알 수 있어야 한다고 봅니다. 따라서 Controller가 특정 기능의 수행 결과를 알 수 있어야 할 거 같아요. Controller에게 전달될 수 있는 결과는 반환된 값 뿐이니, 이 부분을 좀 생각해볼 필요가 있겠네요.
> 
> 저도 마찬가지로 코드를 수정할 필요가 있는 것 같습니다.

그럼 UserController에서 addReview를 호출할 때 catchError를 사용해 구현하면 될까요?