feature:  Owner E2E test
SHSongs/cheese-shop pull request #31
Opened 2023-09-24 13:43 UTC by darkenpeng

- Owner와 관련된 E2E test를 작성하였습니다.
- 리팩토링 및 오타를 수정하였습니다.

2023-09-24 13:55 UTC, darkenpeng commented
로컬에서 통과되는 테스트들이 GitHub Actions의 Test에서 통과되지 않아 review.json, reservation.json을 add 하였습니다.

2023-09-24 14:05 UTC, ycheese requested changes

2023-09-24 14:05 UTC, ycheese commented on src/test/scala/MySuite.scala
> +        _ = assertTrue(response.status == Status.Ok)
이 부분이 yield에 포함되어야 할 것 같은데 어떻게 생각하시나요?

2023-09-24 14:05 UTC, ycheese commented on src/test/scala/MySuite.scala
> +      } yield assertTrue(result.isRight)
실제로 예약이 종료되었는지 확인하는 코드(`Reservation.isClosed == true`)도 있으면 좋겠습니다

2023-09-24 14:07 UTC, darkenpeng commented on src/test/scala/MySuite.scala
> +        _ = assertTrue(response.status == Status.Ok)
제가 assertTrue 두개를 연달아서 쓰는 걸 못해서 저렇게 했는데 혹시 어떻게 하는지 알려주실 수 있을까요?

2023-09-24 14:11 UTC, ycheese commented on src/test/scala/MySuite.scala
> +        _ = assertTrue(response.status == Status.Ok)
이 코드로 예를 들자면
`yield assertTrue(response.status == Status.Ok && result.isRight)`
이렇게 가능하겠네요!

2023-09-24 14:17 UTC, darkenpeng commented on src/test/scala/MySuite.scala
> +        _ = assertTrue(response.status == Status.Ok)
저도 처음에 그렇게 작성을 했었는데 디버깅할 때 어느 쪽이 True인지 확인하기가 힘들 것 같아서 분리했어요!
이런 경우에는 어떻게 assertTrue를 두 번 쓸 수 있을까요?

2023-09-24 14:27 UTC, darkenpeng commented on src/test/scala/MySuite.scala
> +        _ = assertTrue(response.status == Status.Ok)
앗 
```scala
assertTrue(A == B) &&
assertTrue( C==D )
```
이런 코드를 발견해서 한번 고쳐보겠습니다~

2023-10-04 15:09 UTC, hatchling13 approved these changes
`Service` 쪽 코드에서 `readJson`, `writeJson`을 직접적으로 호출하는 코드는 이후에 `Repository`를 사용하도록 변경하면 될 것 같습니다! 별도로 이슈를 파서 작업할 수도 있고 여기다 추가로 넣어주셔도 될 것 같아요.

또한 문제 해결을 위해 작성되었지만 완료된 주석은 삭제 처리해주셔도 좋겠습니다!

2023-10-05 05:22 UTC, ycheese approved these changes
👍

2023-10-05 05:22 UTC, merged